# Generated by Django 5.2.3 on 2025-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=20)),
                ('ingredients', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
