# Generated by Django 5.2.3 on 2025-07-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='homePage',
        ),
    ]
